name: Merge any release branch to uat
on:
  push:
    branches:
      - 'master'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Merge feature/xxx -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: develop
          github_token: [GITHUB_TOKEN]
