name: PRs to master
on: 
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: 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

      - name: master back to develop
        run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff master -m "Auto-merge master back to develop"
          git push