name: PRs to master
on: 
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - name: assigning token
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.personal_access_token }}
      - name: master back to develop
      run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff master -m "Auto-merge master back to develop"
          git push